
GRANT ALL PRIVILEGES ON DATABASE "DefaultDbName"    TO zuev56;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bot TO zuev56;
GRANT ALL PRIVILEGES ON SCHEMA bot                  TO zuev56;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA bot TO zuev56;

GRANT CONNECT        ON DATABASE "DefaultDbName"    TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bot TO app;
GRANT ALL PRIVILEGES ON SCHEMA bot                  TO app;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA bot TO app;
