GRANT CONNECT        ON DATABASE "DefaultDbName"   TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA zl TO app;
GRANT ALL PRIVILEGES ON SCHEMA zl                  TO app;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA zl TO app;