
GRANT ALL PRIVILEGES ON DATABASE "ZsBot"            TO zuev56;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA zl  TO zuev56;
GRANT ALL PRIVILEGES ON DATABASE "ZsBot"            TO zuev56;
GRANT ALL PRIVILEGES ON SCHEMA zl                   TO zuev56;
GRANT ALL PRIVILEGES ON SCHEMA bot                  TO zuev56;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA zl  TO zuev56;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA bot TO zuev56;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bot TO zuev56;

GRANT CONNECT        ON DATABASE "ZsBot"            TO app;
GRANT ALL PRIVILEGES ON SCHEMA zl                   TO app;
GRANT ALL PRIVILEGES ON SCHEMA bot                  TO app;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA bot TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bot TO app;
GRANT INSERT         ON ALL TABLES    IN SCHEMA bot TO app;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA zl  TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA zl  TO app;
