
GRANT ALL PRIVILEGES ON DATABASE "VkUserWatcher"   TO zuev56;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vk TO zuev56;
GRANT ALL PRIVILEGES ON SCHEMA vk                  TO zuev56;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA vk TO zuev56;

GRANT CONNECT        ON DATABASE "VkUserWatcher"   TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vk TO app;
GRANT ALL PRIVILEGES ON SCHEMA vk                  TO app;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA vk TO app;
